const AppActionTypes = {
    CHANGE_TAB: 'CHANGE_TAB',
    CHANGE_SUBMIT_BUTTON_STATE: 'CHANGE_SUBMIT_BUTTON_STATE',
    SHOW_VALIDATION_ERROR: 'SHOW_VALIDATION_ERROR',
    OPEN_COLOR_PICKER: 'OPEN_COLOR_PICKER',
    CLOSE_COLOR_PICKER: 'CLOSE_COLOR_PICKER'
}

export default AppActionTypes;