const AppActionTypes = {
    CHANGE_TAB: 'CHANGE_TAB',
    CHANGE_SUBMIT_BUTTON_STATE: 'CHANGE_SUBMIT_BUTTON_STATE',
    SHOW_VALIDATION_ERROR: 'SHOW_VALIDATION_ERROR'
}

export default AppActionTypes;