const ImageActionTypes = {
    SELECT_IMAGE_FILE: 'SELECT_IMAGE_FILE',
    COPY_PALETTES: 'COPY_PALEYTTES',
    SELECT_DOT_NUMBER: 'SELECT_DOT_NUMBER',
    SELECT_PALETTE_COLOR: 'SELECT_PALETTE_COLOR',
    SET_COLOR_PALETTES: 'SET_COLOR_PALETTES',
    SET_DOT_IMAGE: 'SET_DOT_IMAGE'
}

module.exports = ImageActionTypes;